### ISSUE TITLE
rendering demo

### ISSUE THREAD

**Issue by strongliang** [creadr/creadr-api#3]
render text with metadata（目前包括词性，分词，拼音）

这是http://thulac.thunlp.org/demo上生成一个例子，简单地做到了分词和词性注释，但是rendering上可以有很多发挥余地
![image](https://cloud.githubusercontent.com/assets/563789/22560214/9a3ee664-e928-11e6-9b34-a3df2d1efc52.png)
- 用颜色或者别的方式显示词性，比如说这个英文例子
![image](https://cloud.githubusercontent.com/assets/563789/22560056/fb9ca942-e927-11e6-9a31-033b7497088b.png)
- 用空格或者别的方式把分词表示出来
- 点击中文的时候，显示拼音。比如说
![image](https://cloud.githubusercontent.com/assets/563789/22560407/5a98add2-e929-11e6-9d2a-4768b07d22ce.png)

assumptions:
- 直接用hardcoded mock data，不需要考虑怎么得到metadata
- 用react实现

**Comment by dekura** [comment]
I have finished the demo and i am afraid to mess up the files in this git repo, so i pushed my code to my github. [ Here is the  link.](https://github.com/chenmo1996/creadr-frontend-demo-v0.1) (https://github.com/chenmo1996/creadr-frontend-demo-v0.1).

**Comment by strongliang** [comment]
nicely done! it's not react, but it gets the job done. we can move on.
